---
- include_vars: db_password.yml
- name: "create container dir"
  file: name=/containers/pg/data state=directory
- name: "ensure postgres container is running"
  docker: image=postgres name=pg ports={{ pg_port }}:{{ pg_port }} volumes=/containers/pg/data:/var/lib/postgresql/data
- name: "ensure database exists"
  docker: 
      image: postgres
      links: "{{ pg_container }}:{{ pg_container }}"
      command: "createdb {{ db_name }} -h {{ pg_container }} -p 5432 -U {{ db_user }}"
      env: "PGPASSWORD={{ db_password }}"
