[database]
    [database.development]
    driver = "postgres"
    open = "postgres://postgres:password@192.168.59.103/abalone?sslmode=disable"
    [database.test]
    driver = "postgres"
    open = "postgres://postgres:password@192.168.59.103/abalonetest?sslmode=disable"
    [database.production]
    driver = "postgres"
    open = "postgres://postgres:$ABDB_PASSWORD@localhost/abalone_production?sslmode=disable"
